import CryptoKit
import Foundation

public struct RenderedLaunchDetails: Equatable, Sendable {
    public var content: String
    public var bodySHA256: String
    public var fileSHA256: String
    public var fileURL: URL

    public init(content: String, bodySHA256: String, fileSHA256: String, fileURL: URL) {
        self.content = content
        self.bodySHA256 = bodySHA256
        self.fileSHA256 = fileSHA256
        self.fileURL = fileURL
    }
}

public enum ManifestDrift: String, Codable, Equatable, Sendable {
    case none
    case missing
    case content
    case permissions
    case contentAndPermissions
}

public struct ManifestInspection: Equatable, Sendable {
    public var path: String
    public var drift: ManifestDrift
    public var expectedHash: String
    public var actualHash: String?
    public var permissions: Int?

    public init(
        path: String,
        drift: ManifestDrift,
        expectedHash: String,
        actualHash: String?,
        permissions: Int?
    ) {
        self.path = path
        self.drift = drift
        self.expectedHash = expectedHash
        self.actualHash = actualHash
        self.permissions = permissions
    }

    public var inSync: Bool { drift == .none }

    public var message: String {
        switch drift {
        case .none:
            return "launch_details.md is synchronized."
        case .missing:
            return "launch_details.md is missing."
        case .content:
            return "launch_details.md content differs from the launcher database."
        case .permissions:
            return "launch_details.md is current but is not read-only (expected mode 0444)."
        case .contentAndPermissions:
            return "launch_details.md content and permissions differ from the launcher database."
        }
    }
}

/// Produces the agent-readable mirror of the SQLite catalog. Environment values are deliberately
/// omitted: only variable names are rendered, so a value cannot leak merely because it was needed
/// at runtime.
public struct MarkdownRenderer: Sendable {
    public static let fileName = "launch_details.md"
    public static let filePermissions = 0o444

    public init() {}

    public func render(project: ProjectRecord, launchers: [LauncherRecord]) -> RenderedLaunchDetails {
        let fileURL = URL(fileURLWithPath: project.directory, isDirectory: true)
            .appendingPathComponent(Self.fileName, isDirectory: false)
        let body = renderBody(project: project, launchers: launchers)
        let bodyHash = Self.sha256Hex(Data(body.utf8))
        let header =
            """
            <!-- GENERATED BY CODEX LAUNCHER — DO NOT EDIT
            schema: \(LauncherSchema.launchDetailsIdentifier)
            project-id: \(project.id.uuidString.lowercased())
            revision: \(project.revision)
            content-sha256: sha256:\(bodyHash)
            -->

            """
        let content = header + body
        return RenderedLaunchDetails(
            content: content,
            bodySHA256: bodyHash,
            fileSHA256: Self.sha256Hex(Data(content.utf8)),
            fileURL: fileURL
        )
    }

    @discardableResult
    public func write(project: ProjectRecord, launchers: [LauncherRecord]) throws -> RenderedLaunchDetails {
        let rendered = render(project: project, launchers: launchers)
        var isDirectory: ObjCBool = false
        guard FileManager.default.fileExists(atPath: project.directory, isDirectory: &isDirectory),
              isDirectory.boolValue else {
            throw LauncherValidationError.invalidDirectory(project.directory)
        }
        try LauncherPaths.atomicWrite(
            Data(rendered.content.utf8),
            to: rendered.fileURL,
            permissions: Self.filePermissions,
            createParentDirectories: false
        )
        return rendered
    }

    public func check(project: ProjectRecord, launchers: [LauncherRecord]) throws -> ManifestInspection {
        let rendered = render(project: project, launchers: launchers)
        guard FileManager.default.fileExists(atPath: rendered.fileURL.path) else {
            return ManifestInspection(
                path: rendered.fileURL.path,
                drift: .missing,
                expectedHash: rendered.fileSHA256,
                actualHash: nil,
                permissions: nil
            )
        }

        let actualData = try Data(contentsOf: rendered.fileURL)
        let actualHash = Self.sha256Hex(actualData)
        let contentMatches = actualData == Data(rendered.content.utf8)
        let attributes = try FileManager.default.attributesOfItem(atPath: rendered.fileURL.path)
        let permissions = (attributes[.posixPermissions] as? NSNumber)?.intValue.mapPermissions
        let permissionsMatch = permissions == Self.filePermissions

        let drift: ManifestDrift
        switch (contentMatches, permissionsMatch) {
        case (true, true): drift = .none
        case (false, true): drift = .content
        case (true, false): drift = .permissions
        case (false, false): drift = .contentAndPermissions
        }
        return ManifestInspection(
            path: rendered.fileURL.path,
            drift: drift,
            expectedHash: rendered.fileSHA256,
            actualHash: actualHash,
            permissions: permissions
        )
    }

    public static func sha256Hex(_ data: Data) -> String {
        SHA256.hash(data: data).map { String(format: "%02x", $0) }.joined()
    }

    private func renderBody(project: ProjectRecord, launchers: [LauncherRecord]) -> String {
        var lines: [String] = []
        lines.append("# Launch details: \(plainHeading(project.displayName))")
        lines.append("")
        lines.append("- Directory: \(codeSpan(project.directory))")
        lines.append("- Project ID: \(codeSpan(project.id.uuidString.lowercased()))")
        lines.append("- Revision: \(project.revision)")
        lines.append("- Source of truth: Launch Station SQLite database; this file is a generated read-only mirror.")
        lines.append("- Retrieve current JSON: \(codeSpan("launch list --directory \(ShellEscaping.quote(project.directory)) --json"))")
        lines.append("")

        let sortedLaunchers = launchers.sorted {
            let left = LauncherValidation.normalizeName($0.name)
            let right = LauncherValidation.normalizeName($1.name)
            return left == right ? $0.id.uuidString < $1.id.uuidString : left < right
        }
        guard !sortedLaunchers.isEmpty else {
            lines.append("_No launchers registered._")
            lines.append("")
            return lines.joined(separator: "\n")
        }

        for launcher in sortedLaunchers {
            lines.append("## \(codeSpan(launcher.name))")
            lines.append("")
            lines.append("- ID: \(codeSpan(launcher.id.uuidString.lowercased()))")
            lines.append("- Description: \(codeSpan(normalizedInline(launcher.description)))")
            if let runDetails = launcher.runDetails, !runDetails.isEmpty {
                lines.append("- Run details: \(codeSpan(normalizedInline(runDetails)))")
            }
            let tags = LauncherValidation.normalizedTags(launcher.tags)
            lines.append("- Tags: \(tags.isEmpty ? "_none_" : tags.map(codeSpan).joined(separator: ", "))")
            lines.append("- Revision: \(launcher.revision)")
            lines.append("- Launch: \(codeSpan("launch \(ShellEscaping.quote(launcher.name))"))")
            lines.append("")

            for action in launcher.sortedActions {
                render(action: action, primary: action.id == launcher.primaryActionID, into: &lines)
            }
        }
        return lines.joined(separator: "\n")
    }

    private func render(action: LaunchAction, primary: Bool, into lines: inout [String]) {
        lines.append("### Action \(codeSpan(action.name))\(primary ? " (primary)" : "")")
        lines.append("")
        lines.append("- ID: \(codeSpan(action.id.uuidString.lowercased()))")
        lines.append("- Description: \(codeSpan(normalizedInline(action.description)))")
        lines.append("- Type: \(codeSpan(action.runner.rawValue))")
        lines.append("- Working directory: \(codeSpan(action.workingDirectory))")
        lines.append("- Required: \(action.required ? "yes" : "no")")
        lines.append("- Runtime arguments: \(action.allowsRuntimeArguments ? "allowed" : "denied")")
        lines.append("- Ready timeout: \(action.readyTimeoutSeconds)s")
        lines.append("- Stop timeout: \(action.stopTimeoutSeconds)s")
        lines.append("- Open target: \(codeSpan(action.openTarget.rawValue))")
        if let bundleIdentifier = action.appBundleIdentifier, !bundleIdentifier.isEmpty {
            lines.append("- App bundle identifier: \(codeSpan(bundleIdentifier))")
        }
        lines.append("- Command:")
        lines.append("")
        lines.append(fencedCode(action.displayCommand, language: "sh"))
        lines.append("")

        let environmentKeys = action.environment.keys.sorted()
        if environmentKeys.isEmpty {
            lines.append("- Environment keys: _none_")
        } else {
            lines.append("- Environment keys (values omitted): \(environmentKeys.map(codeSpan).joined(separator: ", "))")
        }
        let inheritedKeys = Array(Set(action.inheritedEnvironment)).sorted()
        lines.append("- Inherited environment: \(inheritedKeys.isEmpty ? "_none_" : inheritedKeys.map(codeSpan).joined(separator: ", "))")

        switch action.port.mode {
        case .none:
            lines.append("- Port: _none_")
        case .automatic:
            lines.append(
                "- Port: automatic \(codeSpan(action.port.logicalName)); env \(codeSpan(action.port.environmentVariable)); host env \(codeSpan(action.port.hostEnvironmentVariable)); lease \(codeSpan(action.port.lease))"
            )
        case .fixed:
            let fixed = action.port.fixedPort.map(String.init) ?? "invalid"
            lines.append(
                "- Port: fixed \(codeSpan(action.port.logicalName)) = \(fixed); env \(codeSpan(action.port.environmentVariable)); host env \(codeSpan(action.port.hostEnvironmentVariable)); lease \(codeSpan(action.port.lease))"
            )
        }
        if let template = action.port.URLTemplate, !template.isEmpty {
            lines.append("- Port URL template: \(codeSpan(template))")
        }
        if let health = action.healthCheckURL, !health.isEmpty {
            lines.append("- Health check: \(codeSpan(health))")
        }
        lines.append("")
    }

    private func plainHeading(_ value: String) -> String {
        value
            .replacingOccurrences(of: "\\", with: "\\\\")
            .replacingOccurrences(of: "#", with: "\\#")
            .replacingOccurrences(of: "\r\n", with: " ")
            .replacingOccurrences(of: "\n", with: " ")
            .replacingOccurrences(of: "\r", with: " ")
    }

    private func normalizedInline(_ value: String) -> String {
        value
            .replacingOccurrences(of: "\r\n", with: "\\n")
            .replacingOccurrences(of: "\n", with: "\\n")
            .replacingOccurrences(of: "\r", with: "\\n")
    }

    private func codeSpan(_ value: String) -> String {
        let longestRun = longestBacktickRun(in: value)
        let fence = String(repeating: "`", count: max(1, longestRun + 1))
        let padded = value.hasPrefix("`") || value.hasSuffix("`") ? " \(value) " : value
        return fence + padded + fence
    }

    private func fencedCode(_ value: String, language: String) -> String {
        let fence = String(repeating: "`", count: max(3, longestBacktickRun(in: value) + 1))
        return "\(fence)\(language)\n\(value)\n\(fence)"
    }

    private func longestBacktickRun(in value: String) -> Int {
        var longest = 0
        var current = 0
        for character in value {
            if character == "`" {
                current += 1
                longest = max(longest, current)
            } else {
                current = 0
            }
        }
        return longest
    }
}

private extension Int {
    var mapPermissions: Int { self & 0o777 }
}
